language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-report=xml --cov=cv_generator tests/
after_success:
  - bash <(curl -s https://codecov.io/bh)